from . import base
from . import patient
from . import drug
from . import lab
from . import visit
from . import consult
from . import pharmacy
from . import ipd
from . import surgery
from . import blood_bank
from . import billing
from . import ai_memory
from . import ai_service
from . import dashboard
from . import config_settings
from . import demo
from . import setup
