{
    "name": "Stratos HMS — Hospital Management & EMR with AI",
    "summary": "One live patient record for the whole hospital: front desk, triage, consults with AI scribe & assist, "
               "lab, pharmacy, wards, theatre, blood bank, billing and a live command centre.",
    "version": "19.0.1.0.0",
    "category": "Industries/Healthcare",
    "author": "Stratos Hub",
    "website": "https://www.stratos-hub.com",
    "license": "LGPL-3",
    "application": True,
    "sequence": 1,
    "depends": ["base", "mail", "account", "product", "web"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        # security
        "security/hms_security.xml",
        "security/ir.model.access.csv",
        "security/hms_rules.xml",
        # data
        "data/sequences.xml",
        "data/hms_data.xml",
        "data/icd10_data.xml",
        "data/drug_data.xml",
        "data/test_data.xml",
        "data/protocol_data.xml",
        # views
        "views/hms_assets_placeholder.xml",
        "views/patient_views.xml",
        "views/visit_views.xml",
        "views/consult_views.xml",
        "views/lab_views.xml",
        "views/pharmacy_views.xml",
        "views/ipd_views.xml",
        "views/surgery_views.xml",
        "views/blood_bank_views.xml",
        "views/billing_views.xml",
        "views/ai_views.xml",
        "views/config_views.xml",
        "views/menus.xml",
        # reports
        "report/report_paperformat.xml",
        "report/report_prescription.xml",
        "report/report_bill.xml",
        "report/report_lab.xml",
        "report/report_discharge.xml",
        "report/report_actions.xml",
        "data/mail_templates.xml",
    ],
    "demo": [
        "demo/demo_users.xml",
        "demo/demo_patients.xml",
        "demo/demo_visits.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "stratos_hms/static/src/scss/hms.scss",
            "stratos_hms/static/src/js/scribe_field.js",
            "stratos_hms/static/src/js/ews_badge.js",
            "stratos_hms/static/src/js/journey_bar.js",
            "stratos_hms/static/src/js/command_center.js",
            "stratos_hms/static/src/xml/scribe_field.xml",
            "stratos_hms/static/src/xml/ews_badge.xml",
            "stratos_hms/static/src/xml/journey_bar.xml",
            "stratos_hms/static/src/xml/command_center.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "images": ["static/description/banner.png"],
}
