{
    "name": "VetCairn Reporting",
    "summary": "Operational veterinary analysis and printable schedules",
    "version": "19.0.1.0.0",
    "category": "Services/Veterinary",
    "author": "VetCairn",
    "license": "LGPL-3",
    "depends": ["vet_reminder"],
    "data": [
        "security/vet_reporting_security.xml",
        "security/ir.model.access.csv",
        "views/vet_appointment_reporting_views.xml",
        "views/vet_clinical_reporting_views.xml",
        "views/vet_vaccination_reporting_views.xml",
        "views/vet_diagnostic_reporting_views.xml",
        "views/vet_prescription_reporting_views.xml",
        "views/vet_inventory_reporting_views.xml",
        "views/vet_billing_reporting_views.xml",
        "views/vet_reminder_reporting_views.xml",
        "reports/vet_appointment_schedule_report.xml",
        "views/vet_reporting_menus.xml",
    ],
    "application": False,
    "installable": True,
}
