{
    "name": "VetCairn Base",
    "summary": "Core veterinary clinics, clients, patients, and staff",
    "version": "19.0.1.0.0",
    "category": "Services/Veterinary",
    "author": "VetCairn",
    "website": "https://vetcairn.example.com",
    "license": "LGPL-3",
    "depends": ["base", "mail", "contacts"],
    "data": [
        "security/vet_base_security.xml",
        "security/ir.model.access.csv",
        "data/vet_patient_sequence.xml",
        "views/vet_species_views.xml",
        "views/vet_breed_views.xml",
        "views/vet_patient_views.xml",
        "views/vet_clinic_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/vet_base_menus.xml",
    ],
    "demo": ["demo/vet_base_demo.xml"],
    "application": True,
    "installable": True,
}
